### PR TITLE
fix: handle `Expr::Binary` properly in `walk_expr`

### PR DESCRIPTION
**Pull request by scintillavoy**
When handling `Expr::Binary` in `walk_expr`, the return values from lhs and rhs are ORed (`||`) but it should be `&&`.

For example, let the expression be `foo{l1="v1"} + bar{l2="v2"}`. `walk_expr` will recurse into lhs (`foo`) first and if the return value is `Ok(true)`, it should recurse into rhs (`bar`) but it would not.

Additionally, there was a small inconsistency in the example (newlines between the output), so I fixed it.

### CODE REVIEW

**Review by waynexia — APPROVED** [review]
Looking great! Thanks for this fixing.


This PR is good enough for merging. It would be better if you are willing to add a unit test to reflect this change!

**Review by evenyag — COMMENTED** [review]
Thanks! Could you please fix the clippy warning?

**Comment by scintillavoy** [comment]
@waynexia

> Looking great! Thanks for this fixing.
> 
> This PR is good enough for merging. It would be better if you are willing to add a unit test to reflect this change!

I added some tests, but I'm new to Rust so please check if I organized the code correctly. 😅

**Comment by scintillavoy** [comment]
@evenyag

> Thanks! Could you please fix the clippy warning?

I checked it, but I have no idea how to fix it. The message says there are possible "refactorings" in the file `promql.y.rs` and it seems it is not introduced by the changes from this PR.

**Review by waynexia — APPROVED** [review]

**Comment by waynexia** [comment]
Thank you @scintillavoy :heart:

**Pull request merged**
