### PR TITLE
fix: unary grammer conflicts

### PR DESCRIPTION
**Pull request by yuanbohan**
## what's included

- omit error in yacc file, for grmtools does not support it. See [Major differences](https://softdevteam.github.io/grmtools/master/book/yacccompatibility.html#major-differences)
- fix unary expr conflicts, and unit tests

## what's next

- fix binary expr rule conflicts

### CODE REVIEW

**Comment by waynexia** [comment]
Is unary expr still conflict with binary expr? I see you change lots about literal and unary expr's rules

**Comment by yuanbohan** [comment]
> Is unary expr still conflict with binary expr? I see you change lots about literal and unary expr's rules

Yes, I'm trying to solve binary expr rule conflicts. But grmtools is somehow hard to debug, any advice?

**Review by evenyag — APPROVED** [review]
LGTM

**Review by waynexia — APPROVED** [review]
Feels good to me

**Pull request merged**
